#!/bin/bash

cd /tmp/rom

./halium/devices/setup halium_arm64
hybris-patches/apply-patches.sh --mb

. build/envsetup.sh
source build/envsetup.sh && breakfast halium_arm64
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

make api-stubs-docs || echo no problem, we need ccache
make system-api-stubs-docs || echo no problem we need ccache
make test-api-stubs-docs || echo no problem, we need ccache
mka rawsystemimage -j$(nproc --all) &

sleep 85m
kill %1
ccache -s
