#!/bin/bash

cd /tmp

com ()
{
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

time rclone copy ccache.tar.gz drive:Share/halium/GSI/halium-10.0-arm64/

cd /tmp/rom
time rclone copy -v out/target/product/halium_arm64/android-rootfs.img drive:Share/halium/GSI/halium-10.0-arm64/
